name: Publish Dev Container Features

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Dev Container CLI
        uses: devcontainers/action@v1

      - name: Publish Features to GHCR
        run: devcontainer features publish --namespace forhad-h --source .

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
